AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sms_reminder

  Sample SAM Template for sms_reminder

Globals:
  Function:
    Timeout: 600
    MemorySize: 128
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON

Resources:
  SmsSendRemindersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sms_reminder_send/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: 
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Outputs:

  SmsSendRemindersFunctionArn:  
    Description: "SMS Send Reminders Lambda Function ARN"
    Value: !GetAtt SmsSendRemindersFunction.Arn

  SmsSendRemindersFunctionIamRole:
    Description: "Implicit IAM Role created for SMS Send Reminders function"
    Value: !GetAtt SmsSendRemindersFunctionRole.Arn